### ISSUE TITLE
New core 'user shares a public link via email' is failing

### ISSUE THREAD

**Issue by phil-davis** [owncloud/encryption#160]
The core issue was fixed in core PR https://github.com/owncloud/core/pull/36393

It fails with master-key encryption https://drone.owncloud.com/owncloud/encryption/988/169/16
```
  Scenario: user shares a public link via email                                                             # /var/www/owncloud/testrunner/tests/acceptance/features/webUISharingPublic/reShareByPublicLink.feature:21
    Given user "user1" has created folder "/simple-folder"                                                  # FeatureContext::userHasCreatedFolder()
    And user "user1" has shared folder "/simple-folder" with user "user2" with permissions "share,read"     # FeatureContext::userHasSharedFileWithUserUsingTheSharingApi()
    And parameter "shareapi_allow_public_notification" of app "core" has been set to "yes"                  # FeatureContext::serverParameterHasBeenSetTo()
    And user "user2" has logged in using the webUI                                                          # WebUILoginContext::theUserLogsInUsingTheWebUI()
INFORMATION: timed out waiting for outstanding ajax calls
    When the user creates a new public link for folder "simple-folder" using the webUI with                 # WebUISharingContext::theUserCreatesANewPublicLinkForFileFolderUsingTheWebUIWith()
      | email | foo@bar.co |
      │ INFORMATION: timed out waiting for outstanding ajax calls
      SensioLabs\Behat\PageObjectExtension\PageObject\Exception\ElementNotFoundException: Page\FilesPageElement\SharingDialogElement\PublicLinkTab::findLinkEntryByName xpath .//*[@class='link-entry--title' and .=%s]/.. could not find link entry with the given name in /var/www/owncloud/testrunner/tests/acceptance/features/lib/OwncloudPage.php:844
      Stack trace:
      #0 /var/www/owncloud/testrunner/tests/acceptance/features/lib/FilesPageElement/SharingDialogElement/PublicLinkTab.php(344): Page\OwncloudPage->assertElementNotNull(NULL, 'Page\\FilesPageE...')
      #1 /var/www/owncloud/testrunner/tests/acceptance/features/lib/FilesPageElement/SharingDialogElement/PublicLinkTab.php(268): Page\FilesPageElement\SharingDialogElement\PublicLinkTab->findLinkEntryByName('Public link')
      #2 /var/www/owncloud/testrunner/tests/acceptance/features/bootstrap/WebUISharingContext.php(509): Page\FilesPageElement\SharingDialogElement\PublicLinkTab->getLinkUrl('Public link')
      #3 [internal function]: WebUISharingContext->theUserCreatesANewPublicLinkForFileFolderUsingTheWebUIWith('simple-folder', Object(Behat\Gherkin\Node\TableNode))
```

and with user-key encryption: https://drone.owncloud.com/owncloud/encryption/988/219/16

Investigate.

**Comment by phil-davis** [comment]
@karakayasemi the previous scenario passes. That does an ordinary public link share of a received share. So this kind of thing seems to be possible with encryption.

Any idea why it will fail when we want to send an email?

**Comment by phil-davis** [comment]
@dpakach I guess we need to skip this scenario on 10.3.0 and 10.3.1
