### ISSUE TITLE
Trashbin and local storage tests failing with encryption

### ISSUE THREAD

**Issue by phil-davis** [owncloud/encryption#244]
https://drone.owncloud.com/owncloud/encryption/1734/53/16
```
--- Failed scenarios:

    /var/www/owncloud/testrunner/tests/acceptance/features/apiTrashbin/trashbinRestore.feature:164
    /var/www/owncloud/testrunner/tests/acceptance/features/apiTrashbin/trashbinRestore.feature:165
    /var/www/owncloud/testrunner/tests/acceptance/features/apiTrashbin/trashbinRestore.feature:170
    /var/www/owncloud/testrunner/tests/acceptance/features/apiTrashbin/trashbinRestore.feature:186
```

The same test scenarios failed with user_ldap + encryption: https://drone.owncloud.com/owncloud/user_ldap/2995/212/19

These started failing last night.

The scenarios pass in core, without encryption. This core PR was merged yesterday: https://github.com/owncloud/core/pull/38375 So maybe that is causing this problem.

Let's see the nightly CI result tonight...

**Comment by phil-davis** [comment]
```
  Scenario Outline: Deleting a file into external storage moves it to the trashbin and can be restored                 # /var/www/owncloud/testrunner/tests/acceptance/features/apiTrashbin/trashbinRestore.feature:145
    Given using <dav-path> DAV path                                                                                    # FeatureContext::usingOldOrNewDavPath()
    And the administrator has invoked occ command "files:scan --all"                                                   # OccContext::theAdministratorHasInvokedOccCommand()
    And user "Alice" has created folder "/local_storage/tmp"                                                           # FeatureContext::userHasCreatedFolder()
    And user "Alice" has moved file "/textfile0.txt" to "/local_storage/tmp/textfile0.txt"                             # FeatureContext::userHasMovedFile()
    And user "Alice" has deleted file "/local_storage/tmp/textfile0.txt"                                               # FeatureContext::userHasDeletedFile()
    And as "Alice" the folder with original path "/local_storage/tmp/textfile0.txt" should exist in the trashbin       # TrashbinContext::elementIsInTrashCheckingOriginalPath()
    When user "Alice" restores the folder with original path "/local_storage/tmp/textfile0.txt" using the trashbin API # TrashbinContext::elementInTrashIsRestored()
    Then the HTTP status code should be "201"                                                                          # FeatureContext::thenTheHTTPStatusCodeShouldBe()
    And the following headers should match these regular expressions for user "Alice"                                  # FeatureContext::headersShouldMatchRegularExpressionsForUser()
      | ETag | /^"[a-f0-9:\.]{1,32}"$/ |
    And as "Alice" the folder with original path "/local_storage/tmp/textfile0.txt" should not exist in the trashbin   # TrashbinContext::elementIsNotInTrashCheckingOriginalPath()
    And the content of file "/local_storage/tmp/textfile0.txt" for user "Alice" should be "file to delete"             # FeatureContext::contentOfFileForUserShouldBe()
    And user "Alice" should see the following elements                                                                 # FeatureContext::userShouldSeeTheElements()
      | /local_storage/                  |
      | /local_storage/tmp/              |
      | /local_storage/tmp/textfile0.txt |

    Examples:
      | dav-path |
      | old      |
        HTTP status code 500 is not the expected value 201
        Failed asserting that 500 matches expected '201'.
      | new      |
        HTTP status code 500 is not the expected value 201
        Failed asserting that 500 matches expected '201'.
```

**Comment by phil-davis** [comment]
```
  Scenario: Deleting an updated file into external storage moves it to the trashbin and can be restored                                        # /var/www/owncloud/testrunner/tests/acceptance/features/apiTrashbin/trashbinRestore.feature:170
    Given using old DAV path                                                                                                                   # FeatureContext::usingOldOrNewDavPath()
    And the administrator has invoked occ command "files:scan --all"                                                                           # OccContext::theAdministratorHasInvokedOccCommand()
    And user "Alice" has created folder "/local_storage/tmp"                                                                                   # FeatureContext::userHasCreatedFolder()
    And user "Alice" has moved file "/textfile0.txt" to "/local_storage/tmp/textfile0.txt"                                                     # FeatureContext::userHasMovedFile()
    And user "Alice" has uploaded chunk file "1" of "1" with "AA" to "/local_storage/tmp/textfile0.txt"                                        # FeatureContext::userHasUploadedChunkedFile()
    And user "Alice" has deleted file "/local_storage/tmp/textfile0.txt"                                                                       # FeatureContext::userHasDeletedFile()
    And as "Alice" the folder with original path "/local_storage/tmp/textfile0.txt" should exist in the trashbin                               # TrashbinContext::elementIsInTrashCheckingOriginalPath()
    When user "Alice" restores the folder with original path "/local_storage/tmp/textfile0.txt" using the trashbin API                         # TrashbinContext::elementInTrashIsRestored()
    Then the HTTP status code should be "201"                                                                                                  # FeatureContext::thenTheHTTPStatusCodeShouldBe()
      HTTP status code 500 is not the expected value 201
      Failed asserting that 500 matches expected '201'.
    And as "Alice" the folder with original path "/local_storage/tmp/textfile0.txt" should not exist in the trashbin                           # TrashbinContext::elementIsNotInTrashCheckingOriginalPath()
    And the downloaded content when downloading file "/local_storage/tmp/textfile0.txt" for user "Alice" with range "bytes=0-1" should be "AA" # FeatureContext::downloadedContentWhenDownloadingForUserWithRangeShouldBe()
``

**Comment by phil-davis** [comment]
```
  Scenario: Deleting an updated file into external storage moves it to the trashbin and can be restored                                        # /var/www/owncloud/testrunner/tests/acceptance/features/apiTrashbin/trashbinRestore.feature:186
    Given using new DAV path                                                                                                                   # FeatureContext::usingOldOrNewDavPath()
    And the administrator has invoked occ command "files:scan --all"                                                                           # OccContext::theAdministratorHasInvokedOccCommand()
    And user "Alice" has created folder "/local_storage/tmp"                                                                                   # FeatureContext::userHasCreatedFolder()
    And user "Alice" has moved file "/textfile0.txt" to "/local_storage/tmp/textfile0.txt"                                                     # FeatureContext::userHasMovedFile()
    And user "Alice" has uploaded the following chunks to "/local_storage/tmp/textfile0.txt" with new chunking                                 # FeatureContext::userHasUploadedTheFollowingChunksUsingNewChunking()
      | number | content |
      | 1      | AA      |
    And user "Alice" has deleted file "/local_storage/tmp/textfile0.txt"                                                                       # FeatureContext::userHasDeletedFile()
    And as "Alice" the folder with original path "/local_storage/tmp/textfile0.txt" should exist in the trashbin                               # TrashbinContext::elementIsInTrashCheckingOriginalPath()
    When user "Alice" restores the folder with original path "/local_storage/tmp/textfile0.txt" using the trashbin API                         # TrashbinContext::elementInTrashIsRestored()
    Then the HTTP status code should be "201"                                                                                                  # FeatureContext::thenTheHTTPStatusCodeShouldBe()
      HTTP status code 500 is not the expected value 201
      Failed asserting that 500 matches expected '201'.
    And as "Alice" the folder with original path "/local_storage/tmp/textfile0.txt" should not exist in the trashbin                           # TrashbinContext::elementIsNotInTrashCheckingOriginalPath()
    And the downloaded content when downloading file "/local_storage/tmp/textfile0.txt" for user "Alice" with range "bytes=0-1" should be "AA" # FeatureContext::downloadedContentWhenDownloadingForUserWithRangeShouldBe()
```

**Comment by phil-davis** [comment]
@jvillafanez maybe there is some clue in https://drone.owncloud.com/owncloud/user_ldap/2995/212/14
```
{"reqId":"jseTgtbej2IjGgwQnL06","level":4,"time":"2021-02-20T02:14:47+00:00","remoteAddr":"192.168.44.9","user":"Alice","app":"webdav","method":"MOVE","url":"\/remote.php\/dav\/trash-bin\/Alice\/2147488408","message":"Exception: Bad Signature: {\"Exception\":\"OC\\\\HintException\",\"Message\":\"Bad Signature\",\"Code\":0,\"Trace\":\"
#0 \\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/encryption\\\/lib\\\/Crypto\\\/Crypt.php(481): OCA\\\\Encryption\\\\Crypto\\\\Crypt->checkSignature('-\\\\xACe;\\\\x94\\\\x10\\\\xD0\\\\xCBL\\\\x04V\\\\n\\\\xCB\\\\xAD', '\\\\xD5\\\\xF7\\\\f\\\\xDA\\\\x89\\\\xCD\\\\f\\\\xB9\\\\xDE\\\\xD2\\\\x16m\\\\xB1\\\\xAB\\\\x9F...', '3525d7e8fd523d2...')\\n
#1 \\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/encryption\\\/lib\\\/Crypto\\\/Encryption.php(373): OCA\\\\Encryption\\\\Crypto\\\\Crypt->symmetricDecryptFileContent('-\\\\xACe;\\\\x94\\\\x10\\\\xD0\\\\xCBL\\\\x04V\\\\n\\\\xCB\\\\xAD0...', '\\\\xD5\\\\xF7\\\\f\\\\xDA\\\\x89\\\\xCD\\\\f\\\\xB9\\\\xDE\\\\xD2\\\\x16m\\\\xB1\\\\xAB\\\\x9F...', 'AES-256-CTR', 2, '0end', true)\\n
#2 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/private\\\/Files\\\/Stream\\\/Encryption.php(473): OCA\\\\Encryption\\\\Crypto\\\\Encryption->decrypt(*** sensitive parameters replaced ***)\\n
#3 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/private\\\/Files\\\/Stream\\\/Encryption.php(289): OC\\\\Files\\\\Stream\\\\Encryption->readCache()\\n
#4 [internal function]: OC\\\\Files\\\\Stream\\\\Encryption->stream_read(14)\\n
#5 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/private\\\/legacy\\\/helper.php(298): fread(Resource id #61, 8192)\\n
#6 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(791): OC_Helper::streamCopy(Resource id #61, Resource id #69)\\n
#7 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(634): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->copyBetweenStorage(Object(OCA\\\\Files_Trashbin\\\\Storage), 'files_trashbin\\\/...', 'tmp\\\/textfile0.t...', true, true)\\n
#8 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(579): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->moveFromStorage(Object(OCA\\\\Files_Trashbin\\\\Storage), 'files_trashbin\\\/...', 'tmp\\\/textfile0.t...')\\n
#9 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(579): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->moveFromStorage(Object(OCA\\\\Files_Trashbin\\\\Storage), 'files_trashbin\\\/...', 'tmp\\\/textfile0.t...')\\n
#10 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/private\\\/Files\\\/View.php(877): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->moveFromStorage(Object(OCA\\\\Files_Trashbin\\\\Storage), 'files_trashbin\\\/...', 'tmp\\\/textfile0.t...')\\n
#11 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/public\\\/Events\\\/EventEmitterTrait.php(50): OC\\\\Files\\\\View->OC\\\\Files\\\\{closure}(*** sensitive parameters replaced ***)\\n
#12 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/private\\\/Files\\\/View.php(919): OC\\\\Files\\\\View->emittingCall(Object(Closure), Array, 'file', 'rename')\\n
#13 \\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/files_trashbin\\\/lib\\\/Trashbin.php(519): OC\\\\Files\\\\View->rename('\\\/files_trashbin...', '\\\/files\\\/local_st...')\\n
#14 \\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/dav\\\/lib\\\/TrashBin\\\/TrashBinManager.php(95): OCA\\\\Files_Trashbin\\\\Trashbin::restore('textfile0.txt.d...', 'textfile0.txt', 1613787285, '\\\/local_storage\\\/...')\\n
#15 \\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/dav\\\/lib\\\/TrashBin\\\/AbstractTrashBinNode.php(127): OCA\\\\DAV\\\\TrashBin\\\\TrashBinManager->restore('Alice', Object(OCA\\\\DAV\\\\TrashBin\\\\TrashBinFile), '\\\/local_storage\\\/...')\\n
#16 \\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(411): OCA\\\\DAV\\\\TrashBin\\\\AbstractTrashBinNode->restore('\\\/local_storage\\\/...')\\n
#17 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(160): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->moveInto('textfile0.txt', 'trash-bin\\\/Alice...', Object(OCA\\\\DAV\\\\TrashBin\\\\TrashBinFile))\\n
#18 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(612): Sabre\\\\DAV\\\\Tree->move('trash-bin\\\/Alice...', 'files\\\/Alice\\\/loc...')\\n
#19 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/WildcardEmitterTrait.php(89): Sabre\\\\DAV\\\\CorePlugin->httpMove(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP
\\\\Response))\\n
#20 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(472): Sabre\\\\DAV\\\\Server->emit('method:MOVE', Array)\\n
#21 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(253): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n
#22 \\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/dav\\\/lib\\\/Server.php(330): Sabre\\\\DAV\\\\Server->start()\\n
#23 \\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n
#24 \\\/var\\\/www\\\/owncloud\\\/server\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n
#25 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/encryption\\\/lib\\\/Crypto\\\/Crypt.php\",\"Line\":504}"}
```

**Comment by karakayasemi** [comment]
@phil-davis can you help me to run CI tests against core/fix-encrypted-storage-copy branch? Thank you.

**Comment by phil-davis** [comment]
@karakayasemi see PR #247

**Comment by karakayasemi** [comment]
@jvillafanez Looks like the encryption wrapper already does not wrap shared storages https://github.com/owncloud/core/blob/5d08c66e5c57b008266da1bbf51e14dbe662ab12/lib/private/Encryption/EncryptionWrapper.php#L68. In the scenario of this ticket https://github.com/owncloud/core/pull/38375, the home storage of the sharer user is used as source storage.

I could not find a way to catch the exact described scenario. What do you think about a solution similar to this PR https://github.com/owncloud/core/pull/38452/files? In my local, it worked for both acceptance tests and the initial issue scenario but seems it broke some acceptance tests move scenarios.

**Comment by jvillafanez** [comment]
But in the scenario described in https://github.com/owncloud/core/pull/38375, the shared file is copied to the owner's trashbin. I guess the uid and and sourceStorage's owner will be the same with your PR in that scenario, which would cause the issue.

> Looks like the encryption wrapper already does not wrap shared storages

How does the sharees decrypt the files then?

**Comment by karakayasemi** [comment]
`uid` is the session user https://github.com/owncloud/core/blob/a539f3f8e5f5cfff42005163e76bb2715980e747/lib/private/Encryption/EncryptionWrapper.php#L85 which is different from sourceStorage's owner in the described scenario in owncloud/core#38375. 
I have not deep knowledge about the most of the cases like encryption with sharing. I am just reading from code and debugging the scenarios.

**Comment by jvillafanez** [comment]
For me it's counter-intuitive, but if there is no better solution will have to use it. Just make sure it's properly commented in order to understand the reason and prevent us to delete it by mistake.

**Comment by karakayasemi** [comment]
@phil-davis at first, only one of the API tests was failing: https://drone.owncloud.com/owncloud/encryption/1738/53/16

But now, `cliCoreUKey-3-3-master-mysql8.0-php7.2` tests started to fail independent from https://github.com/owncloud/core/pull/38375 because of another reason.

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/encryption/1754/114/11
```
  Scenario Outline: Admin resets user password with special characters                                                      # /var/www/owncloud/testrunner/tests/acceptance/features/cliProvisioning/editUser.feature:57
    Given user "brand-new-user" has been deleted                                                                            # FeatureContext::userHasBeenDeleted()
    When the administrator creates user "brand-new-user" password "%alt1%" group "brand-new-group" using the occ command    # OccUsersGroupsContext::theAdministratorCreatesUserPasswordGroupUsingTheOccCommand()
    And user "brand-new-user" uploads file with content "some text" to "atextfile.txt" using the WebDAV API                 # FeatureContext::userUploadsAFileWithContentTo()
    And the administrator resets the password of user "brand-new-user" to "<password>" using the occ command                # OccUsersGroupsContext::resetUserPasswordUsingTheOccCommand()
    Then the command should have been successful                                                                            # OccContext::theCommandShouldHaveBeenSuccessful()
    And the command output should contain the text 'Successfully reset password for %username%' about user "brand-new-user" # OccContext::theCommandOutputContainsTheTextAboutUser()
    And user "brand-new-user" should exist                                                                                  # FeatureContext::userShouldExist()
    And the content of file "atextfile.txt" for user "brand-new-user" using password "<password>" should be "some text"     # FeatureContext::contentOfFileForUserUsingPasswordShouldBe()
    But user "brand-new-user" using password "%alt1%" should not be able to download file "atextfile.txt"                   # FeatureContext::userUsingPasswordShouldNotBeAbleToDownloadFile()

    Examples:
      | password                     | comment                               |
      | !@#$%^&*()-_+=[]{}:;,.<>?~/\ | special characters                    |
        The downloaded content was expected to be 'some text', but actually is '<?xml version="1.0" encoding="utf-8"?>
        <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
          <s:exception>Sabre\DAV\Exception\Forbidden</s:exception>
          <s:message>Encryption not ready: Private Key missing for user: please try to log-out and log-in again</s:message>
        </d:error>
        '. HTTP status was 403
        Failed asserting that two strings are equal.
        --- Expected
        +++ Actual
        @@ @@
        -'some text'
        +'<?xml version="1.0" encoding="utf-8"?>\n
        +<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">\n
        +  <s:exception>Sabre\DAV\Exception\Forbidden</s:exception>\n
        +  <s:message>Encryption not ready: Private Key missing for user: please try to log-out and log-in again</s:message>\n
        +</d:error>\n
        +'
      | España§àôœ€                  | special European and other characters |
        The downloaded content was expected to be 'some text', but actually is '<?xml version="1.0" encoding="utf-8"?>
        <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
          <s:exception>Sabre\DAV\Exception\Forbidden</s:exception>
          <s:message>Encryption not ready: Private Key missing for user: please try to log-out and log-in again</s:message>
        </d:error>
        '. HTTP status was 403
        Failed asserting that two strings are equal.
        --- Expected
        +++ Actual
        @@ @@
        -'some text'
        +'<?xml version="1.0" encoding="utf-8"?>\n
        +<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">\n
        +  <s:exception>Sabre\DAV\Exception\Forbidden</s:exception>\n
        +  <s:message>Encryption not ready: Private Key missing for user: please try to log-out and log-in again</s:message>\n
        +</d:error>\n
        +'
      | नेपाली                       | Unicode                               |
        The downloaded content was expected to be 'some text', but actually is '<?xml version="1.0" encoding="utf-8"?>
        <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
          <s:exception>Sabre\DAV\Exception\Forbidden</s:exception>
          <s:message>Encryption not ready: Private Key missing for user: please try to log-out and log-in again</s:message>
        </d:error>
        '. HTTP status was 403
        Failed asserting that two strings are equal.
        --- Expected
        +++ Actual
        @@ @@
        -'some text'
        +'<?xml version="1.0" encoding="utf-8"?>\n
        +<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">\n
        +  <s:exception>Sabre\DAV\Exception\Forbidden</s:exception>\n
        +  <s:message>Encryption not ready: Private Key missing for user: please try to log-out and log-in again</s:message>\n
        +</d:error>\n
        +'
      | password with spaces         | password with spaces                  |
        The downloaded content was expected to be 'some text', but actually is '<?xml version="1.0" encoding="utf-8"?>
        <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
          <s:exception>Sabre\DAV\Exception\Forbidden</s:exception>
          <s:message>Encryption not ready: Private Key missing for user: please try to log-out and log-in again</s:message>
        </d:error>
        '. HTTP status was 403
        Failed asserting that two strings are equal.
        --- Expected
        +++ Actual
        @@ @@
        -'some text'
        +'<?xml version="1.0" encoding="utf-8"?>\n
        +<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">\n
        +  <s:exception>Sabre\DAV\Exception\Forbidden</s:exception>\n
        +  <s:message>Encryption not ready: Private Key missing for user: please try to log-out and log-in again</s:message>\n
        +</d:error>\n
        +'
```

I wonder why that failed? 

Note: the daily-master-qa tarball had not been updating "for a while". It was fixed yesterday. So tests are now running against the latest core master code. Whatever broke this would be something merged to master in the last week or so.
