### ISSUE TITLE
local storage tests failing with user-key encryption

### ISSUE THREAD

**Issue by phil-davis** [owncloud/encryption#320]
and against 10.9.1RC1

https://drone.owncloud.com/owncloud/user_ldap/3689/142/16
and
https://drone.owncloud.com/owncloud/user_ldap/3690/142/16

```
runsh: Total unexpected failed scenarios throughout the test run:
cliLocalStorage/propfindOnLocalStorage.feature:32
cliLocalStorage/propfindOnLocalStorage.feature:51
cliLocalStorage/propfindOnLocalStorage.feature:52
cliLocalStorage/propfindOnLocalStorage.feature:65
cliLocalStorage/propfindOnLocalStorage.feature:66
cliLocalStorage/propfindOnLocalStorage.feature:80
cliLocalStorage/propfindOnLocalStorage.feature:81
cliLocalStorage/propfindOnLocalStorageOc10Issue39470.feature:31
cliLocalStorage/propfindOnLocalStorageOc10Issue39470.feature:32
cliLocalStorage/propfindOnLocalStorageOc10Issue39470.feature:53
cliLocalStorage/propfindOnLocalStorageOc10Issue39470.feature:54
```

```
Feature: get file info using PROPFIND

  Background:                                                                                                    # /var/www/owncloud/testrunner/tests/acceptance/features/cliLocalStorage/propfindOnLocalStorage.feature:4
    Given these users have been created with default attributes and without skeleton files:                      # FeatureContext::theseUsersHaveBeenCreatedWithDefaultAttributesAndWithoutSkeletonFiles()
      | username |
      | Alice    |
      | Brian    |
    And the administrator has created the local storage mount "local_storage2"                                   # OccContext::theAdministratorHasCreatedTheLocalStorageMountUsingTheOccCommand()
    And the administrator has created the local storage mount "local_storage3"                                   # OccContext::theAdministratorHasCreatedTheLocalStorageMountUsingTheOccCommand()
    And user "Alice" has uploaded file with content "some data" to "/local_storage2/textfile0.txt"               # FeatureContext::userHasUploadedAFileWithContentTo()
    And user "Alice" has created folder "/local_storage2/simple-folder"                                          # FeatureContext::userHasCreatedFolder()
    And user "Alice" has uploaded file with content "some data" to "/local_storage2/simple-folder/textfile1.txt" # FeatureContext::userHasUploadedAFileWithContentTo()
    And user "Alice" has created folder "/local_storage3/PARENT"                                                 # FeatureContext::userHasCreatedFolder()
    And user "Alice" has created folder "/FOLDER"                                                                # FeatureContext::userHasCreatedFolder()
    And user "Alice" has uploaded file with content "some data" to "/local_storage3/PARENT/PARENT.txt"           # FeatureContext::userHasUploadedAFileWithContentTo()

  Scenario Outline: list files on root folder with external storage with depth 1     # /var/www/owncloud/testrunner/tests/acceptance/features/cliLocalStorage/propfindOnLocalStorage.feature:19
    Given using <dav_version> DAV path                                               # FeatureContext::usingOldOrNewDavPath()
    When user "Alice" lists the resources in "/" with depth "1" using the WebDAV API # FeatureContext::userListsTheResourcesInPathWithDepthUsingTheWebdavApi()
    Then the HTTP status code should be "207"                                        # FeatureContext::thenTheHTTPStatusCodeShouldBe()
    And the propfind result of user "Alice" should contain only these entries:       # FeatureContext::thePropfindResultShouldContainOnlyEntries()
      | /               |
      | /local_storage2 |
      | /local_storage  |
      | /local_storage3 |
      | /FOLDER         |

    Examples:
      | dav_version |
      | old         |
      | new         |
        HTTP status code was not 201 or 204 while trying to upload file '/local_storage2/textfile0.txt' for user 'Alice'
        Failed asserting that an array contains 503.

  Scenario Outline: list files on root folder with external storage using depth infinity    # /var/www/owncloud/testrunner/tests/acceptance/features/cliLocalStorage/propfindOnLocalStorage.feature:34
    Given using <dav_version> DAV path                                                      # FeatureContext::usingOldOrNewDavPath()
    When user "Alice" lists the resources in "/" with depth "infinity" using the WebDAV API # FeatureContext::userListsTheResourcesInPathWithDepthUsingTheWebdavApi()
    Then the HTTP status code should be "207"                                               # FeatureContext::thenTheHTTPStatusCodeShouldBe()
    And the propfind result of user "Alice" should contain only these entries:              # FeatureContext::thePropfindResultShouldContainOnlyEntries()
      | /                                           |
      | /local_storage2                             |
      | /local_storage                              |
      | /local_storage3                             |
      | /FOLDER                                     |
      | /local_storage3/PARENT                      |
      | /local_storage3/PARENT/PARENT.txt           |
      | /local_storage2/textfile0.txt               |
      | /local_storage2/simple-folder               |
      | /local_storage2/simple-folder/textfile1.txt |

    Examples:
      | dav_version |
      | old         |
        HTTP status code was not 201 or 204 while trying to upload file '/local_storage2/textfile0.txt' for user 'Alice'
        Failed asserting that an array contains 503.
      | new         |
        HTTP status code was not 201 or 204 while trying to upload file '/local_storage2/textfile0.txt' for user 'Alice'
        Failed asserting that an array contains 503.
```

https://drone.owncloud.com/owncloud/user_ldap/3689/142/10

```
{"reqId":"n9H0t1iPXADfk60159Pi","level":4,"time":"2022-01-02T00:45:41+00:00","remoteAddr":"192.168.19.7","user":"Alice","app":"webdav","method":"PUT",
"url":"\/remote.php\/webdav\/local_storage2\/textfile0.txt",
"message":"Exception: HTTP\/1.1 503 Encryption not ready: multikeydecrypt with share key failed:error:0909006C:PEM routines:get_name:no start line: 
{\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",
\"Message\":\"Encryption not ready: multikeydecrypt with share key failed:error:0909006C:PEM routines:get_name:no start line\",\"Code\":0,\"Trace\":\"
#0 \\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(243): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->convertToSabreException(Object(OCA\\\\Encryption\\\\Exceptions\\\\MultiKeyDecryptException))\\n
owncloud/user_ldap#1 \\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(173): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id owncloud/user_ldap#549)\\n
owncloud/user_ldap#2 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1098): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('textfile0.txt', Resource id owncloud/user_ldap#549)\\n
owncloud/user_ldap#3 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(504): Sabre\\\\DAV\\\\Server->createFile('local_storage2\\\/...', Resource id owncloud/user_ldap#549, NULL)\\n
owncloud/user_ldap#4 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/WildcardEmitterTrait.php(89): Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n
owncloud/user_ldap#5 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(472): Sabre\\\\DAV\\\\Server->emit('method:PUT', Array)\\n
owncloud/user_ldap#6 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(253): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n
owncloud/user_ldap#7 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(321): Sabre\\\\DAV\\\\Server->start()\\n
owncloud/user_ldap#8 \\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(67): Sabre\\\\DAV\\\\Server->exec()\\n
owncloud/user_ldap#9 \\\/var\\\/www\\\/owncloud\\\/server\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n
owncloud/user_ldap#10 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":696}"}
```

Notes:
- the tests pass with user_ldap and master-key encryption https://drone.owncloud.com/owncloud/user_ldap/3690/167/16
- the first scenario is passing, so there might be some problem with deleting and re-creating the local storage between scenarios

**Comment by saw-jan** [comment]
Steps: (core latest, coreRC1)
1. Enable encryption with `user-specific` key
2. Run localStorage cli tests

I looked through the issue and the following are my findings:
- first test gets passed
- the later tests will fail in step `user "Alice" has uploaded file with content "some data" to "/local_storage2/textfile0.txt"` with `503` status code
server log:
```
{"reqId":"n9H0t1iPXADfk60159Pi","level":4,"time":"2022-01-02T00:45:41+00:00","remoteAddr":"192.168.19.7","user":"Alice","app":"webdav","method":"PUT",
"url":"\/remote.php\/webdav\/local_storage2\/textfile0.txt",
"message":"Exception: HTTP\/1.1 503 Encryption not ready: multikeydecrypt with share key failed:error:0909006C:PEM routines:get_name:no start line: 
{\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",
\"Message\":\"Encryption not ready: multikeydecrypt with share key failed:error:0909006C:PEM routines:get_name:no start line\",\"Code\":0,\"Trace\":\"
#0 \\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(243): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->convertToSabreException(Object(OCA\\\\Encryption\\\\Exceptions\\\\MultiKeyDecryptException))\\n
owncloud/user_ldap#1 \\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(173): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id owncloud/user_ldap#549)\\n
owncloud/user_ldap#2 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1098): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('textfile0.txt', Resource id owncloud/user_ldap#549)\\n
owncloud/user_ldap#3 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(504): Sabre\\\\DAV\\\\Server->createFile('local_storage2\\\/...', Resource id owncloud/user_ldap#549, NULL)\\n
owncloud/user_ldap#4 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/WildcardEmitterTrait.php(89): Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n
owncloud/user_ldap#5 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(472): Sabre\\\\DAV\\\\Server->emit('method:PUT', Array)\\n
owncloud/user_ldap#6 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(253): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n
owncloud/user_ldap#7 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(321): Sabre\\\\DAV\\\\Server->start()\\n
owncloud/user_ldap#8 \\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(67): Sabre\\\\DAV\\\\Server->exec()\\n
owncloud/user_ldap#9 \\\/var\\\/www\\\/owncloud\\\/server\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n
owncloud/user_ldap#10 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":696}"}
```
Checks:
- [x] created local-storage folders have been deleted after a test scenario ends
- [x] server shows no local storage after a test scenario ends
- [ ] getting local storages from cli returns zero result

**Comment by phil-davis** [comment]
Thanks @saw-jan 

It seems that if we create a local storage mount, use it, then delete it (and delete users), then create the local storage again, make it available to some user. Then when the user tries to upload to that storage they get this `503 Encryption not ready` failure.

Maybe there is a simpler sequence that will cause this to happen?

I will ping developers about this and see if they need more investigation or...

**Comment by JanAckermann** [comment]
Did you tried to reproduce it manually?

```
➜  core git:(5627304b42) ✗ curl -i -XPROPFIND http://owncloud.local/remote.php/webdav -u admin:admin -H "depth: 1"
HTTP/1.1 207 Multi-Status
Date: Tue, 04 Jan 2022 12:37:48 GMT
Server: Apache/2.4.41 (Ubuntu)
X-Content-Type-Options: nosniff
X-XSS-Protection: 0
X-Robots-Tag: none
X-Frame-Options: SAMEORIGIN
X-Download-Options: noopen
X-Permitted-Cross-Domain-Policies: none
Set-Cookie: ocgvjmf4aher=53s1tld36s1hurvfv5sstrb39n; path=/; HttpOnly; SameSite=Strict
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: oc_sessionPassphrase=Kj2yh402z4bhhguLOZkw758YMhoS%2FXGpWyV%2BhjN5KMfygGNaHM4kSwqrZZLWPs3Y6gm6k3MQVT%2FvwuA1u3cL4QxfR4WLwe28G%2F83XdN7Y8Z5yAosVjBCF1yXdWKm08ZR; path=/; HttpOnly; SameSite=Strict
Content-Security-Policy: default-src 'none';
Set-Cookie: ocgvjmf4aher=lob609g5tfutscq3re7hgjfd8j; path=/; HttpOnly; SameSite=Strict
Set-Cookie: cookie_test=test; expires=Tue, 04-Jan-2022 13:37:48 GMT; Max-Age=3600
Vary: Brief,Prefer
DAV: 1, 3, extended-mkcol, 2
Content-Length: 959
Content-Type: application/xml; charset=utf-8

<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns"><d:response><d:href>/remote.php/webdav/</d:href><d:propstat><d:prop><d:getlastmodified>Tue, 04 Jan 2022 12:37:43 GMT</d:getlastmodified><d:resourcetype><d:collection/></d:resourcetype><d:quota-used-bytes>13</d:quota-used-bytes><d:quota-available-bytes>-3</d:quota-available-bytes><d:getetag>&quot;1e4b0273d92c42a197cfb6b3be6f5288&quot;</d:getetag></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response><d:response><d:href>/remote.php/webdav/Local/</d:href><d:propstat><d:prop><d:getlastmodified>Tue, 04 Jan 2022 12:36:48 GMT</d:getlastmodified><d:resourcetype><d:collection/></d:resourcetype><d:quota-used-bytes>13</d:quota-used-bytes><d:quota-available-bytes>-3</d:quota-available-bytes><d:getetag>&quot;61d43f605c5a1&quot;</d:getetag></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response></d:multistatus>
➜  core git:(5627304b42) ✗ curl -u admin:admin -X PROPFIND -i http://owncloud.local/remote.php/dav/files/admin/ -H "depth: 1"
HTTP/1.1 207 Multi-Status
Date: Tue, 04 Jan 2022 12:38:24 GMT
Server: Apache/2.4.41 (Ubuntu)
X-Content-Type-Options: nosniff
X-XSS-Protection: 0
X-Robots-Tag: none
X-Frame-Options: SAMEORIGIN
X-Download-Options: noopen
X-Permitted-Cross-Domain-Policies: none
Set-Cookie: ocgvjmf4aher=ip0ft9tnkt1c40pmndi56v7677; path=/; HttpOnly; SameSite=Strict
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: oc_sessionPassphrase=G18%2F6FcNMZGNCCCpykYDlcpgCAJ9cFd9wUJFg7NDEtZAoRVE%2BqWi1tS9Rl%2FQL5MP3v8m1zehELSN3opwIm37hzqF8nZ%2Bcak3a%2B5m4hb7USpHiqmmrcvYPDSuV7DBWd12; path=/; HttpOnly; SameSite=Strict
Content-Security-Policy: default-src 'none';
Set-Cookie: ocgvjmf4aher=jmsg05ibitgka9qgnbaclnmfvo; path=/; HttpOnly; SameSite=Strict
Set-Cookie: cookie_test=test; expires=Tue, 04-Jan-2022 13:38:24 GMT; Max-Age=3600
Vary: Brief,Prefer
DAV: 1, 3, extended-mkcol, 2
Content-Length: 977
Content-Type: application/xml; charset=utf-8

<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns"><d:response><d:href>/remote.php/dav/files/admin/</d:href><d:propstat><d:prop><d:getlastmodified>Tue, 04 Jan 2022 12:37:43 GMT</d:getlastmodified><d:resourcetype><d:collection/></d:resourcetype><d:quota-used-bytes>13</d:quota-used-bytes><d:quota-available-bytes>-3</d:quota-available-bytes><d:getetag>&quot;1e4b0273d92c42a197cfb6b3be6f5288&quot;</d:getetag></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response><d:response><d:href>/remote.php/dav/files/admin/Local/</d:href><d:propstat><d:prop><d:getlastmodified>Tue, 04 Jan 2022 12:36:48 GMT</d:getlastmodified><d:resourcetype><d:collection/></d:resourcetype><d:quota-used-bytes>13</d:quota-used-bytes><d:quota-available-bytes>-3</d:quota-available-bytes><d:getetag>&quot;61d43f605c5a1&quot;</d:getetag></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response></d:multistatus>
```

I followed the steps and can't reproduce the error

**Comment by phil-davis** [comment]
Note: https://drone.owncloud.com/owncloud/user_ldap/3710/142/16

user-key encryption plus user_ldap gets run each night, and of course it fails because of this issue.

I will sort out some relevant skipping so we can get CI runs to to pass.
