### ISSUE TITLE
Failing test scenarios week of 7 March 2022

### ISSUE THREAD

**Issue by phil-davis** [owncloud/encryption#329]
Example from this morning's CI:
https://drone.owncloud.com/owncloud/encryption/2343/21/11
```
runsh: Total unexpected failed scenarios throughout the test run:
apiEncryption/encoding.feature:38
apiEncryption/encoding.feature:45
apiEncryption/encoding.feature:82
apiEncryption/encoding.feature:93
```

Example test output:
```
    Then the content of file "/textfile1.txt" for user "Brian" should be "some data"                                          # FeatureContext::contentOfFileForUserShouldBe()
      The downloaded content was expected to be 'some data', but actually is '<?xml ver'. HTTP status was 500
```

Log:
```
{"reqId":"V4x50QOGOQAi6BAlDcjA","level":4,"time":"2022-03-10T00:57:36+00:00","remoteAddr":"192.168.5.4","user":"Brian","app":"webdav","method":"GET","url":"\/remote.php\/webdav\/textfile1.txt",
"message":"Exception: Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.: {\"Exception\":\"OC\\\\Encryption\\\\Exceptions\\\\DecryptionFailedException\",\"Message\":\"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.\",\"Code\":0,\"Trace\":\"
#0 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/private\\\/Files\\\/Stream\\\/Encryption.php(478): OCA\\\\Encryption\\\\Crypto\\\\Encryption->decrypt(*** sensitive parameters replaced ***)\\n
#1 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/private\\\/Files\\\/Stream\\\/Encryption.php(294): OC\\\\Files\\\\Stream\\\\Encryption->readCache()\\n
#2 [internal function]: OC\\\\Files\\\\Stream\\\\Encryption->stream_read()\\n
#3 \\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/Wrapper.php(55): fread()\\n
#4 \\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/CallbackWrapper.php(96): Icewind\\\\Streams\\\\Wrapper->stream_read()\\n
#5 [internal function]: Icewind\\\\Streams\\\\CallbackWrapper->stream_read()\\n
#6 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/composer\\\/sabre\\\/http\\\/lib\\\/Sapi.php(112): stream_copy_to_stream()\\n
#7 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(490): Sabre\\\\HTTP\\\\Sapi::sendResponse()\\n
#8 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(253): Sabre\\\\DAV\\\\Server->invokeMethod()\\n
#9 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(321): Sabre\\\\DAV\\\\Server->start()\\n
#10 \\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(67): Sabre\\\\DAV\\\\Server->exec()\\n
#11 \\\/var\\\/www\\\/owncloud\\\/server\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n
#12 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/encryption\\\/lib\\\/Crypto\\\/Encryption.php\",\"Line\":374}"}
```

Happens with user-key encryption.

Also https://drone.owncloud.com/owncloud/encryption/2343/25/15 has webUI scenarios failing:
```
runsh: Total unexpected failed scenarios throughout the test run:
webUIUserKeysType/userKeys.feature:60
webUIUserKeysType/userKeys.feature:61
```

**Comment by phil-davis** [comment]
@jvillafanez looks similar to https://github.com/owncloud/ransomware_protection/issues/287 - maybe the same cause?

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/encryption/2362/20/11
```
runsh: Total unexpected failed scenarios throughout the test run:
apiEncryption/encoding.feature:38
apiEncryption/encoding.feature:45
apiEncryption/encoding.feature:82
apiEncryption/encoding.feature:93
```
Still getting 500 HTTP status

**Comment by jvillafanez** [comment]
https://github.com/owncloud/core/pull/39908 should fix https://drone.owncloud.com/owncloud/encryption/2362/20/11
I'm not sure about the other one. I haven't reproduced the issue with the patch, but maybe I used the wrong steps.

**Comment by phil-davis** [comment]
I merged https://github.com/owncloud/core/pull/39908 to core, so that will get in the daily-master-qa tarball and nightly encryption tests will run with it. I will also re-run #331

**Comment by phil-davis** [comment]
nightly encryption CI passed this morning: https://drone.owncloud.com/owncloud/encryption/2365

so previous regressions ahve been fixed, without introducing and other failures - great stuff. Closing this issue.
