### ISSUE TITLE
recreating masterkey produces Exception messages in log file

### ISSUE THREAD

**Issue by individual-it** [owncloud/encryption#45]
1. run `occ encryption:recreate-master-key`
2. observe the log file

```
{"reqId":"6OLZNauZWjbIiflpvADi","level":3,"time":"2018-08-16T08:58:14+00:00","remoteAddr":"","user":"--","app":"no app in context","method":"--","url":"--","message":"Exception: {\"Exception\":\"OC\\\\Encryption\\\\Exceptions\\\\DecryptionFailedException\",\"Message\":\"Encryption library: Decryption (symmetric) of content failed: error:0607A082:digital envelope routines:EVP_CIPHER_CTX_set_key_length:invalid key length\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/encryption\\\/lib\\\/Crypto\\\/Crypt.php(469): OCA\\\\Encryption\\\\Crypto\\\\Crypt->decrypt(*** sensitive parameters replaced ***)\\n#1 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/encryption\\\/lib\\\/Crypto\\\/Encryption.php(369): OCA\\\\Encryption\\\\Crypto\\\\Crypt->symmetricDecryptFileContent('ownCloud test t...', '\\\\xF8\\\\x03A\\\\xA5\\\\x94\\\\x19\\\\x06X\\\\xC1\\\\xDB.\\\/\\\"\\\\xC06...', 'AES-128-CFB', 1, '0end')\\n#2 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(587): OCA\\\\Encryption\\\\Crypto\\\\Encryption->decrypt(*** sensitive parameters replaced ***)\\n#3 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(507): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->fixUnencryptedSize('files\\\/PARENT\\\/CH...', 24, 24)\\n#4 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(187): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->verifyUnencryptedSize('files\\\/PARENT\\\/CH...', 24)\\n#5 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Checksum.php(202): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->getMetaData('files\\\/PARENT\\\/CH...')\\n#6 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(576): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Checksum->getMetaData('files\\\/PARENT\\\/CH...')\\n#7 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/Files\\\/Cache\\\/Scanner.php(116): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->getMetaData('files\\\/PARENT\\\/CH...')\\n#8 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/Files\\\/Cache\\\/Scanner.php(153): OC\\\\Files\\\\Cache\\\\Scanner->getData('files\\\/PARENT\\\/CH...')\\n#9 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/Files\\\/Cache\\\/Scanner.php(326): OC\\\\Files\\\\Cache\\\\Scanner->scanFile('files\\\/PARENT\\\/CH...', 3, -1, NULL, false)\\n#10 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/Files\\\/Cache\\\/Updater.php(124): OC\\\\Files\\\\Cache\\\\Scanner->scan('files\\\/PARENT\\\/CH...', false, 3, false)\\n#11 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/Files\\\/View.php(325): OC\\\\Files\\\\Cache\\\\Updater->update('files\\\/PARENT\\\/CH...', 1534409894)\\n#12 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/Files\\\/View.php(845): OC\\\\Files\\\\View->writeUpdate(Object(OCA\\\\Files_Trashbin\\\\Storage), 'files\\\/PARENT\\\/CH...')\\n#13 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/public\\\/Events\\\/EventEmitterTrait.php(50): OC\\\\Files\\\\View->OC\\\\Files\\\\{closure}(Array)\\n#14 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/Files\\\/View.php(881): OC\\\\Files\\\\View->emittingCall(Object(Closure), Array, 'file', 'rename')\\n#15 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/Encryption\\\/DecryptAll.php(274): OC\\\\Files\\\\View->rename('\\\/admin\\\/files\\\/PA...', '\\\/admin\\\/files\\\/PA...')\\n#16 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/Encryption\\\/DecryptAll.php(239): OC\\\\Encryption\\\\DecryptAll->decryptFile('\\\/admin\\\/files\\\/PA...')\\n#17 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/Encryption\\\/DecryptAll.php(183): OC\\\\Encryption\\\\DecryptAll->decryptUsersFiles('admin', Object(Symfony\\\\Component\\\\Console\\\\Helper\\\\ProgressBar), 'admin (1 of 1)')\\n#18 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/User\\\/Manager.php(438): OC\\\\Encryption\\\\DecryptAll->OC\\\\Encryption\\\\{closure}(Object(OC\\\\User\\\\User))\\n#19 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/User\\\/AccountMapper.php(231): OC\\\\User\\\\Manager->OC\\\\User\\\\{closure}(Object(OC\\\\User\\\\Account))\\n#20 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/User\\\/Manager.php(439): OC\\\\User\\\\AccountMapper->callForAllUsers(Object(Closure), '', true)\\n#21 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/User\\\/Manager.php(457): OC\\\\User\\\\Manager->callForAllUsers(Object(Closure), '', true)\\n#22 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/Encryption\\\/DecryptAll.php(186): OC\\\\User\\\\Manager->callForSeenUsers(Object(Closure))\\n#23 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/Encryption\\\/DecryptAll.php(108): OC\\\\Encryption\\\\DecryptAll->decryptAllUsersFiles('')\\n#24 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/encryption\\\/lib\\\/Command\\\/RecreateMasterKey.php(244): OC\\\\Encryption\\\\DecryptAll->decryptAll(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#25 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/encryption\\\/lib\\\/Command\\\/RecreateMasterKey.php(182): OCA\\\\Encryption\\\\Command\\\\RecreateMasterKey->decryptAllUsers(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#26 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/symfony\\\/console\\\/Command\\\/Command.php(251): OCA\\\\Encryption\\\\Command\\\\RecreateMasterKey->execute(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#27 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/symfony\\\/console\\\/Application.php(946): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#28 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/symfony\\\/console\\\/Application.php(248): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand(Object(OCA\\\\Encryption\\\\Command\\\\RecreateMasterKey), Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#29 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/symfony\\\/console\\\/Application.php(148): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#30 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/Console\\\/Application.php(161): Symfony\\\\Component\\\\Console\\\\Application->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#31 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/console.php(106): OC\\\\Console\\\\Application->run()\\n#32 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/occ(11): require_once('\\\/home\\\/artur\\\/www...')\\n#33 {main}\",\"File\":\"\\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/encryption\\\/lib\\\/Crypto\\\/Crypt.php\",\"Line\":587}"}

**Comment by PVince81** [comment]
@sharidas can you recheck in case it's a regression of some sorts ? (only reproduction is enough and compare with the version where you fixed it)

**Comment by sharidas** [comment]
In the mater branch of core + encryption, this is reproducible. ( core commit -> 8425d3b8729c057d4eb3f5593f8e1693ea6adffb and encryption commit -> dd84426a21291ba980f9977baf519972d18bb64e).

When I move the git HEAD to commit 39e9ce228ac8ea52fd257a129507acce10686d86 ( commit message - "Fix recreate masterkey issue when decryptall command used" ) in the stable10 branch, the log doesn't appear. 

Require bisecting.

**Comment by sharidas** [comment]
Git bisect says https://github.com/owncloud/core/commit/70fea3233f5f68ec39749a5f2fc54819411818b3 is the commit causing the exception. Debugging furhter.

**Comment by sharidas** [comment]
Precisely call in this line causes the exception https://github.com/owncloud/core/blob/stable10/lib/private/Files/Storage/Wrapper/Encryption.php#L507

**Comment by sharidas** [comment]
It looks like the usage of appending `.part` is causing the exception. I will get the detailed code flow that is causing the issue.

**Comment by sharidas** [comment]
I have observed that in the view->rename(), call made at https://github.com/owncloud/core/blob/stable10/lib/private/Encryption/DecryptAll.php#L274

The code doesn't execute either of the block at https://github.com/owncloud/core/blob/stable10/lib/private/Files/View.php#L792-L804. This is because of the append `.part`. When I try to remove the `.part` and revert the line in DecryptAll.php to `$target = $path . '.decrypted.' . $this->getTimestamp();` this exception is not thrown.
