### ISSUE TITLE
core acceptance test fileDetails.feature:44 failing

### ISSUE THREAD

**Issue by phil-davis** [owncloud/encryption#60]
This scenario fails a lot when run with encryption, e,g, https://drone.owncloud.com/owncloud/encryption/244/541
```
  Scenario: user shares a file through public link and then the details dialog should work in a Shared by link page # /var/www/owncloud/tests/acceptance/features/webUIFiles/fileDetails.feature:44
    Given the user has created a new public link for the folder "simple-folder" using the webUI                     # WebUISharingContext::theUserCreatesANewPublicLinkForUsingTheWebUI()
    When the user browses to the shared-by-link page                                                                # WebUIFilesContext::theUserBrowsesToTheSharedByLinkPage()
    Then the folder "simple-folder" should be listed on the webUI                                                   # WebUIFilesContext::theFileFolderShouldBeListedOnTheWebUI()
    When the user opens the file action menu of the folder "simple-folder" in the webUI                             # WebUIFilesContext::theUserOpensTheFileActionMenuOfTheFolderInTheWebui()
    And the user clicks the details file action in the webUI                                                        # WebUIFilesContext::theUserClicksTheFileActionInTheWebui()
    Then the details dialog should be visible in the webUI                                                          # WebUIFilesContext::theDetailsDialogShouldBeVisibleInTheWebui()
    And the thumbnail should be visible in the details panel                                                        # WebUIFilesContext::theThumbnailShouldBeVisibleInTheDetailsPanel()
      WebDriver\Exception\StaleElementReference: stale element reference: element is not attached to the page document
        (Session info: chrome=69.0.3497.100)
        (Driver info: chromedriver=2.42.591071 (0b695ff80972cc1a65a5cd643186d2ae582cd4ac),platform=Linux 4.4.0-135-generic x86_64) in /var/www/owncloud/lib/composer/instaclick/php-webdriver/lib/WebDriver/Exception.php:155
      Stack trace:
      #0 /var/www/owncloud/lib/composer/instaclick/php-webdriver/lib/WebDriver/AbstractWebDriver.php(157): WebDriver\Exception::factory(10, 'stale element r...')
      #1 /var/www/owncloud/lib/composer/instaclick/php-webdriver/lib/WebDriver/AbstractWebDriver.php(218): WebDriver\AbstractWebDriver->curl('POST', '/execute', Array)
      #2 /var/www/owncloud/lib/composer/instaclick/php-webdriver/lib/WebDriver/Container.php(224): WebDriver\AbstractWebDriver->__call('execute', Array)
      #3 /var/www/owncloud/lib/composer/behat/mink-selenium2-driver/src/Selenium2Driver.php(288): WebDriver\Container->__call('execute', Array)
      #4 /var/www/owncloud/lib/composer/behat/mink-selenium2-driver/src/Selenium2Driver.php(263): Behat\Mink\Driver\Selenium2Driver->executeJsOnElement(Object(WebDriver\Element), 'return argument...', true)
      #5 /var/www/owncloud/lib/composer/behat/mink-selenium2-driver/src/Selenium2Driver.php(554): Behat\Mink\Driver\Selenium2Driver->executeJsOnXpath('((//html/.//*[c...', 'return {{ELEMEN...')
      #6 /var/www/owncloud/lib/composer/behat/mink/src/Element/NodeElement.php(129): Behat\Mink\Driver\Selenium2Driver->getAttribute('((//html/.//*[c...', 'style')
      #7 /var/www/owncloud/tests/acceptance/features/bootstrap/WebUIFilesContext.php(287): Behat\Mink\Element\NodeElement->getAttribute('style')
      #8 [internal function]: WebUIFilesContext->theThumbnailShouldBeVisibleInTheDetailsPanel()
      #9 /var/www/owncloud/lib/composer/behat/behat/src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php(109): 
```

Most likely there is some test timing issue related to the thumbnail being generated more slowly when encryption is on?

**Comment by PVince81** [comment]
thumbnail generation is likely slower, yes

**Comment by individual-it** [comment]
seems not to happen since a while, closing?

**Comment by phil-davis** [comment]
yes, we are not seeing this issue recently. I know there have been other test timing things sorted out in core in the last month, so likely that has helped here.
